sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '6'
  - '4'
before_script:
  - npm i -g codecov
script:
  - npm test
after_success:
  - codecov
  - npm run semantic-release
branches:
  only:
    - master
